In [2]:
import torch

In [3]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
y=torch.tensor([[1,1],[2,2]])
y

tensor([[1, 1],
        [2, 2]])

In [7]:
y.numel()

4

In [9]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y
# 按元素进行

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [23]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).reshape(3,4)

In [24]:
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [25]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X.sum()

tensor(66.)

In [27]:
X.mean()

tensor(5.5000)

In [28]:
X.max()

tensor(11.)

In [29]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a+b
# broadcast

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [31]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[1]=torch.tensor([1,2,3,4])

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[0:2,:]=12

In [37]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [39]:
before=id(Y)
before

139709490071232

In [40]:
Y=Y+X

In [41]:
id(Y)==before,id(Y)

(False, 139709481712880)

In [42]:
Z=torch.zeros_like(Y)
print("id(Z):",id(Z))
Z[:]=X+Y
print("id(Z)",id(Z))

id(Z): 139709484548744
id(Z) 139709484548744


In [44]:
before=id(X)
X+=Y
id(X)==before
# 特别大的矩阵要注意不要反复赋值

True

In [45]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [46]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [5]:
# 数据预处理
# 人工数据集
import os

os.makedirs(os.path.join(".","data"),exist_ok=True)
data_file=os.path.join(".","data","house_tiny.csv")
with open(data_file,"w") as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [6]:
import pandas as pd

In [7]:
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [4]:
data

NumRooms     Alley     Price
0  NA.Pave  127500.0       NaN
1        2       NaN  106000.0
2        4       NaN  178100.0
3      NaN       NaN  140000.0

In [19]:
# 如何处理缺失数据
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]

In [20]:
inputs,outputs

(   NumRooms Alley
 0       NaN  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       NaN   NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [21]:
inputs=inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [22]:
# 字符串变成一类 缺失的为一类
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [23]:
import torch

In [24]:
x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [25]:
# float64 默认浮点数 但是计算慢 深度学习默认float32

In [26]:
#view & reshape reshape=创建一个view
a=torch.arange(12)

In [27]:
b=a.reshape((3,4))

In [28]:
a,b

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [29]:
b[:]=2
# 尽量不要去改东西

In [30]:
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
# 线性代数

In [1]:
import torch

In [4]:
# 标量
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
# 向量（标量值组成的List）
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [10]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B.T==B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
x=torch.arange(24).reshape(2,3,4)

In [14]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #分配新内存 B=A类似指针
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [16]:
A*B #Hadamard product

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [18]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [26]:
A=torch.arange(40,dtype=torch.float32).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [27]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape,A

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [28]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape,A

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [29]:
# 两个维度求和
A_sum_axis01=A.sum(axis=[0,1])
A_sum_axis01,A_sum_axis01.shape

(tensor([180., 190., 200., 210.]), torch.Size([4]))

In [31]:
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [32]:
A.mean(axis=0)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

In [34]:
A.sum(axis=0)/A.shape[0]

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

In [35]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [36]:
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [37]:
A,A.cumsum(axis=2)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[  0.,   1.,   3.,   6.],
          [  4.,   9.,  15.,  22.],
          [  8.,  17.,  27.,  38.],
          [ 12.,  25.,  39.,  54.],
          [ 16.,  33.,  51.,  70.]],
 
         [[ 20.,  41.,  63.,  86.],
          [ 24.,  49.,  75., 102.],
          [ 28.,  57.,  87., 118.],
          [ 32.,  65.,  99., 134.],
          [ 36.,  73., 111., 150.]]]))

In [40]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))