In [1]:
!nvidia-smi

Tue Sep  6 09:43:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.19       Driver Version: 472.19       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8    13W /  N/A |    164MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
# 默认在CPU运算 要指定GPU
import torch
from torch import nn
# 不写默认是第0个
torch.device("cpu"),torch.cuda.device("cuda"),torch.cuda.device("cuda:1")

(device(type='cpu'),
 <torch.cuda.device at 0x1dfcf8af390>)

In [6]:
torch.cuda.device_count()

1

In [7]:
# 返回一个GPU
def try_gpu(i=0):
    if torch.cuda.device_count()>=i+1:
        return torch.device(f"cuda:{i}")
    return torch.device("cpu")

In [8]:
# 返回所有的GPU
def try_all_gpus():
    devices=[
        torch.device(f"cuda:{i}")for i in range(torch.cuda.device_count())
    ]
    return devices if devices else [torch.device("cpu")]

In [9]:
try_gpu()

device(type='cuda', index=0)

In [10]:
try_all_gpus()

[device(type='cuda', index=0)]

In [11]:
try_gpu(10)

device(type='cpu')

In [12]:
x=torch.tensor([1,2,3])
x.device

device(type='cpu')

In [13]:
X=torch.ones(2,3,device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [14]:
Y=torch.rand(2,3,device=try_gpu(0))
Y

tensor([[0.7153, 0.9889, 0.3381],
        [0.5069, 0.8858, 0.8742]], device='cuda:0')

In [15]:
Z=X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [16]:
# 神经网络与GPU
net=nn.Sequential(nn.Linear(3,1))
net=net.to(device=try_gpu())

In [17]:
net(X)

tensor([[-0.9507],
        [-0.9507]], device='cuda:0', grad_fn=<AddmmBackward>)

In [18]:
net[0].weight.data.device

device(type='cuda', index=0)

In [21]:
# 购买 GPU
# 显存 & 计算能力 & 价格
# 同一型号差别是核的个数
# 买新不买旧,买合适价格的
# 内存很贵,一般不需要(对深度学习作用不大)
# data preprocess 不一定在GPU上快,可以留给CPU
# GPU使用命令
a=torch.tensor([1,2,3],device="cuda")
a.cuda(0)
device=torch.device("cuda")
a.to(device)

tensor([1, 2, 3], device='cuda:0')