In [1]:
import numpy as np

In [2]:
V=np.array([1,8,4])
print(np.diag(V))

[[1 0 0]
 [0 8 0]
 [0 0 4]]


In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a=np.array(range(4)).reshape(2,2)
b=np.array(range(4,8)).reshape(2,2)
a*b

array([[ 0,  5],
       [12, 21]])

In [5]:
c=a@b
c

array([[ 6,  7],
       [26, 31]])

In [7]:
c=np.dot(a,b)
c

array([[ 6,  7],
       [26, 31]])

In [8]:
ma=np.asmatrix(a)
mb=np.asmatrix(b)
mc=ma*mb
mc

matrix([[ 6,  7],
        [26, 31]])

In [10]:
a=np.diag([1,2,3])
print(a)
v,e=np.linalg.eig(a)
print(v)
print(e)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(a*a*a)
print(a**3)
print((a**2)*a)
print(a@a@a)

[[ 1  0  0]
 [ 0  8  0]
 [ 0  0 27]]
[[ 1  0  0]
 [ 0  8  0]
 [ 0  0 27]]
[[ 1  0  0]
 [ 0  8  0]
 [ 0  0 27]]
[[ 1  0  0]
 [ 0  8  0]
 [ 0  0 27]]


In [15]:
a=np.diag([1.,2.,3.])
a**(-1)
# 仍然用的hadamard product

c:\ProgramData\Anaconda3\envs\ogb\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  


array([[1.        ,        inf,        inf],
       [       inf, 0.5       ,        inf],
       [       inf,        inf, 0.33333333]])

In [17]:
print(np.linalg.inv(a))
# 矩阵对象
A=np.matrix(a)
print(A.I)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


In [24]:
a=np.random.randn(3,3)
a,np.linalg.inv(a),a@np.linalg.inv(a)

(array([[ 0.3755793 , -1.61781262, -1.32033481],
        [-0.93994993,  2.15532157,  0.41512538],
        [ 1.19006424,  0.63855885,  0.2256686 ]]),
 array([[ 0.07093577, -0.15322129,  0.69688477],
        [ 0.22634138,  0.53081357,  0.34782075],
        [-1.01454262, -0.69399339, -0.22795225]]),
 array([[ 1.00000000e+00, -4.27067375e-17, -1.13829935e-17],
        [-3.66489212e-17,  1.00000000e+00, -1.38782342e-16],
        [ 1.07334096e-17,  9.10952865e-18,  1.00000000e+00]]))

In [25]:
a=np.diag([1,2,3])
b=np.ones([3,3])
a@b,b@a

(array([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]]),
 array([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]))

In [28]:
# 度矩阵 和 邻接矩阵
D=np.diag([2,3,2,3,3,1])
D

array([[2, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 1]])

In [30]:
A=np.array(
    [[0,1,0,0,1,0],
     [1,0,1,0,1,0],
     [0,1,0,1,0,1],
     [0,0,1,0,1,1],
     [1,1,0,1,0,0],
     [0,0,0,1,0,0]]
)
A

array([[0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [31]:
# 获取有向图的长边和短边
W=np.array(
    [[0,0,1,0],
     [1,0,0,0],
     [0,0,0,1],
     [0,0,1.1,0]],
    dtype=np.float32
)
W

array([[0. , 0. , 1. , 0. ],
       [1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. ],
       [0. , 0. , 1.1, 0. ]], dtype=float32)

In [36]:
W<W.T

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False, False, False]])

In [34]:
W*(W<W.T)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)

In [35]:
W-W*(W<W.T)
# W*(W>W.T)

array([[0. , 0. , 1. , 0. ],
       [1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 1.1, 0. ]], dtype=float32)

In [37]:
W>W.T

array([[False, False,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [38]:
# E_long + E_short = W

In [40]:
# 将有向图转成无向图的邻接矩阵
# 保留图中的长边矩阵
# 然后将其中的连接变成双向连接

In [43]:
E_long=W*(W>W.T)
E=E_long+E_long.T
E

array([[0. , 1. , 1. , 0. ],
       [1. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 1.1],
       [0. , 0. , 1.1, 0. ]], dtype=float32)

In [44]:
# 出现长度相同的边容易出问题
W = np.array(
    [[0, 0, 1, 0],
     [1, 0, 0, 1],
     [0, 0, 0, 1],
     [0, 1, 1.1, 0]],
    dtype=np.float32
)
W


array([[0. , 0. , 1. , 0. ],
       [1. , 0. , 0. , 1. ],
       [0. , 0. , 0. , 1. ],
       [0. , 1. , 1.1, 0. ]], dtype=float32)

In [46]:
E_long = W*(W >= W.T)
E = E_long+E_long.T
E


array([[0. , 1. , 1. , 0. ],
       [1. , 0. , 0. , 2. ],
       [1. , 0. , 0. , 1.1],
       [0. , 2. , 1.1, 0. ]], dtype=float32)

In [47]:
E_long_1=W*(W>W.T)
E_long_2=W*(W>=W.T)
E=E_long_1+E_long_2.T
E

array([[0. , 1. , 1. , 0. ],
       [1. , 0. , 0. , 1. ],
       [1. , 0. , 0. , 1.1],
       [0. , 1. , 1.1, 0. ]], dtype=float32)

In [50]:
from pathlib import Path 
import numpy as np 
import pandas as pd 
from scipy.sparse import coo_matrix,csr_matrix,diags,eye 

import torch 
from torch import nn 
import torch.nn.functional as F 

import matplotlib as plt 

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

path=Path("data/cora")
print(path)

cuda
data\cora
