In [1]:
import torch
import torch_geometric

In [3]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
data.x,data.edge_index

(tensor([[-1.],
         [ 0.],
         [ 1.]]),
 tensor([[0, 1, 1, 2],
         [1, 0, 2, 1]]))

In [4]:
print(data.keys)

['edge_index', 'x']


In [5]:
print(data['x'])

tensor([[-1.],
        [ 0.],
        [ 1.]])


In [6]:
for key, item in data:
    print(f'{key} found in data')

x found in data
edge_index found in data


In [7]:
'edge_attr' in data

False

In [8]:
data.num_nodes

3

In [9]:
data.num_edges

4

In [10]:
data.num_node_features

1

In [11]:
data.has_isolated_nodes()

False

In [12]:
data.has_self_loops()

False

In [13]:
data.is_directed()

False

In [14]:
device = torch.device('cuda')
data = data.to(device)

In [15]:
from torch_geometric.datasets import TUDataset

In [16]:
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')

Extracting /tmp/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [17]:
len(dataset)

600

In [18]:
dataset.num_classes

6

In [19]:
dataset.num_node_features

3

In [23]:
data = dataset[0]
data.edge_index

tensor([[ 0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
          3,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
          7,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12,
         12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16,
         16, 16, 17, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 20,
         21, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25,
         25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28,
         28, 28, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 32,
         32, 32, 32, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 35, 35, 35,
         35, 35, 36, 36, 36, 36],
        [ 1,  2,  3,  0,  2,  3, 24, 27,  0,  1,  3, 27, 28,  0,  1,  2,  4,  5,
         28,  3,  5,  6, 29,  3,  4,  6,  7, 29,  4,  5,  7,  8,  5,  6,  8,  9,
         10,  6,  7,  9,  7,  8, 10, 11, 12,  7,  9, 11, 12,  9, 10, 12, 26

In [24]:
data.is_undirected()

True

In [25]:
dataset = dataset.shuffle()

In [26]:
perm = torch.randperm(len(dataset))
dataset = dataset[perm]

In [39]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/home/suzhang/data/Cora', name='Cora')

Processing...
Done!


In [40]:
len(dataset),dataset.num_classes,dataset.num_node_features

(1, 7, 1433)

In [42]:
data = dataset[0]
data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [43]:
data.is_undirected()

True

In [44]:
data.train_mask.sum().item()

140

In [45]:
data.val_mask.sum().item()

500

In [46]:
data.test_mask.sum().item()

1000